### ISSUE TITLE
Issue with Git Action Workflow Validator on Handling Empty Entries

### ISSUE THREAD

**Issue by ROBdk97** [Dymerz/StarCitizen-Localization#257]
**Description:**

**Problem:**

The current Git Action workflow validator fails to handle empty entries appropriately. When encountering an empty entry in the format of:

```ini
Mtps_killallcreatures_multitype__hard_desc_01=
```

The validator mistakenly reports it as missing, even though it's a valid entry according to the source file (in this case, the English `global.ini`).

**Expected Behavior:**

The validator should recognize empty entries as valid, reflecting the behavior of the source file.

**Steps to Reproduce:**

1. Include an empty entry in the format specified above in the source file.
2. Run the Git Action workflow validator.

**Actual Result:**

The validator reports the empty entry as missing, leading to a false-positive error:

```
Validating keys...
  
Unable to find key "Mtps_killallcreatures_multitype__hard_desc_01"
=> 🔥 One or more keys are missing in source file
```

**Expected Result:**

The validator should recognize the empty entry as valid, without reporting it as missing:

```
Validating keys...
  
No missing keys found in the source file.
```

**Comment by Dymerz** [comment]
Nice catch!
I'm working on a fix

**Comment by Dymerz** [comment]
I am able to reproduce this behavior, but I don't fully understand the problem. In my view, all keys defined in `english/global.ini` should be included in the target `.ini` file. This is important because if the game fails to resolve a key in the translation file, the key will be displayed in the game UI/GUI, which should be avoided.

In the specific scenario:
```ini
# ./reference.ini
Mtps_killallcreatures_multitype__hard_desc_01=
```
```ini
# ./target.ini
Mtps_killallcreatures_multitype__hard_desc_01=
```

No errors are triggered, which suggests that the key is properly handled in this case. 

Could you provide more context or details about any potential issues you've observed?

**Comment by ROBdk97** [comment]
I messed up. It's missing in the German global.ini and not the English one.
