### ISSUE TITLE
Can you create a folder for Portuguese_Portugal ?

### ISSUE THREAD

**Issue by DavidFFerreira** [Dymerz/StarCitizen-Localization#415]
Can you create a folder for Portuguese_Portugal ?
I will do the complete translation

**Comment by ROBdk97** [comment]
Portuguese (Portugal) is not officially supported as a localization language. 

Currently, the officially supported languages by CIG are:  
- Chinese (Simplified)  
- Chinese (Traditional)  
- English  
- French (France)  
- German (Germany)  
- Italian (Italy)  
- Japanese (Japan)  
- Korean (South Korea)  
- Polish (Poland)  
- Portuguese (Brazil)  
- Spanish (Latin America)  
- Spanish (Spain)  

For more details, see: [Star Citizen Community Localization Update](https://robertsspaceindustries.com/spectrum/community/SC/forum/1/thread/star-citizen-community-localization-update)

The issue is that if you add `g_language = portuguese_(portugal)` to the `user.cfg` file and create a `portuguese_(portugal)` folder, the game will still run in English because Portuguese (Portugal) is not officially supported.  

The only workaround is to reuse the `portuguese_(brazil)` folder (as it is similar) and place the `portuguese_(portugal)` `global.ini` file into it.

**Comment by ROBdk97** [comment]
@DavidFFerreira  Do you still have any open questions or concerns, or can we close your issue?
